# Generated by Django 2.0.5 on 2018-06-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_course_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_accessed',
            field=models.DateTimeField(null=True),
        ),
    ]
