# Generated by Django 2.0.5 on 2018-06-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_subscription_last_accessed'),
        ('api', '0015_user_avatar'),
    ]

    operations = [
    ]
