# Generated by Django 2.0.5 on 2018-06-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20180628_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='short_name',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
