# Generated by Django 2.0.5 on 2018-07-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_language_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
